frontend:
  image:
    repository: crspo/care-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
    targetPort: 80
  containerPort: 80

backend:
  image:
    repository: your-dockerhub-username/care-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 5000
    targetPort: 5000
  containerPort: 5000

ingress:
  enabled: true
  className: nginx
  hosts:
    - careinourhand.com.au
    - www.careinourhand.com.au
  tls:
    enabled: true
    secretName: care-app-tls
    issuerName: letsencrypt-prod

