frontend:
  image:
    repository: chandansyd05/care-frontend
    tag: 709b82e49b74daef8a3617569afbe94bb0f6b97b
  service:
    port: 80
    targetPort: 80
  containerPort: 80

backend:
  image:
    repository: chandansyd05/care-backend
    tag: 6b842d24a05f030a7429d35d4a243e3f3abc6efc
  service:
    port: 5000
    targetPort: 5000
  containerPort: 5000

ingress:
  enabled: true
  className: nginx
  hosts:
    - careinourhand.com.au
    - www.careinourhand.com.au
  tls:
    enabled: true
    secretName: care-app-tls
    issuerName: letsencrypt-prod

