name: Build and Deploy Backend

on:
  push:
    branches: [ feature ]

jobs:
  build-and-push:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/care-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/care-backend:latest

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.1

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Validate cluster access
        run: kubectl cluster-info

      - name: Delete existing Deployment
        run: kubectl delete deployment/care-app-backend --namespace default --ignore-not-found

      - name: Helm upgrade backend
        run: |
          helm upgrade --install care-app ./helm \
            --namespace default \
            --wait \
            --set backend.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/care-backend \
            --set backend.image.tag=latest

      - name: Verify Deployment
        run: kubectl rollout status deployment/care-app-backend --namespace default

      - name: Clean up old images (optional)
        run: |
          docker image prune -af