name: Build and Deploy Frontend

on:
  push:
    branches: [ feature ]

jobs:
  build-and-push:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/care-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/care-frontend:latest

      - name: Set up Helm
        uses: azure/setup-helm@v2
        with:
          version: v3.13.1

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Validate cluster access
        run: kubectl cluster-info

      - name: Delete existing Deployment
        run: kubectl delete deployment/care-app-frontend --namespace default --ignore-not-found

      - name: Helm upgrade frontend
        run: |
          helm upgrade --install care-app ./helm \
            --namespace default \
            --wait \
            --set frontend.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/care-frontend \
            --set frontend.image.tag=latest

      - name: Verify Deployment
        run: kubectl rollout status deployment/care-app-frontend --namespace default