name: Build, Push, and Deploy Frontend

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  frontend-deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/care-frontend:${{ github.sha }} ./frontend

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/care-frontend:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Helm upgrade frontend
        run: |
          helm upgrade --install care-app ./helm \
            --namespace default \
            --set frontend.image.repository=${{ secrets.DOCKER_USERNAME }}/care-frontend \
            --set frontend.image.tag=${{ github.sha }}

