name: Build, Push, and Deploy Flask App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Optimize images
        run: |
          npm install sharp
          npm run optimize-images

      - name: Replace original images
        run: |
          rm -rf static/images
          mv static/images-optimized static/images


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/care-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/care-app:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml


      - name: Delete existing deployment (if exists)
        run: |
          kubectl get deployment care-app --namespace default && \
          kubectl delete deployment care-app --namespace default || \
          echo "No existing deployment to delete"

      - name: Helm upgrade
        run: |
          helm upgrade --install care-app ./helm \
            --namespace default \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/care-app \
            --set image.tag=${{ github.sha }}

